platform :ios,"8.0"
target "Vcoze" do
pod "MJRefresh"
pod "SDWebImage"
pod "AFNetworking"
pod "MJExtension"
pod "Masonry"
pod "TYPagerController"
pod "SDCycleScrollView",'~> 1.75'
pod "FBSDKLoginKit"
pod "pop"
pod "MBProgressHUD"
pod "MarqueeLabel"
pod "TYAttributedLabel"
pod "RegexKitLite"
pod "UMengAnalytics-NO-IDFA"
pod "JPush"
pod "mob_smssdk"
pod "MMDrawerController"
pod "SVGAPlayer"
pod "ZBLiveBarrage"
pod "mob_sharesdk/ShareSDKPlatforms/Facebook"
pod "AgoraRtcEngine_iOS"

end
